### ISSUE TITLE
Add file rules to turn errors into warnings

### ISSUE THREAD

**Issue by Ramblurr** [mizdra/eslint-interactive#212]
Instead of disabling rules entirely, I like to turn them into warnings so they aren't totally forgotten about.

I do this by adding a file level comment (at the top) with `/*eslint name-of-rule:1,name-of-other-rule:1 */`

This lets us ignore lint errors on old legacy code, but still keep it visible.

Any chance you could add this option to eslint-interactive?

**Comment by mizdra** [comment]
Thanks for the feature request!

I believe that feature can be added. Perhaps add a "Convert to warning" action.

However, `eslint-interactive` by default displays not only errors but also warnings in the table. So, even if you fix a problem in a line to a warning, the table will still show the problem in that line. This can be confusing to users.

Perhaps the --quiet option should be added to `eslint-interactive` to allow the "Convert error to warning" action to run only when that option is enabled.

**Comment by mizdra** [comment]
@Ramblurr Does https://github.com/mizdra/eslint-interactive/issues/212#issuecomment-1153419041 satisfy your use case? If YES, I will try to implement it. If NO, please provide details of your use case.

**Comment by Ramblurr** [comment]
Thanks! Yes that sounds fine. Personally I think it would be fine to show that option even in the case where warnings are shown. Maybe you could add a [warning] or [error] tag to make it clear. And then only show the convert option when it is an error.

**Comment by mizdra** [comment]
I see. There is certainly no need to make the `--quiet` option required. I will try to implement it.

**Comment by mizdra** [comment]
This feature was released in [v10.0.0](https://github.com/mizdra/eslint-interactive/releases/tag/v10.0.0). Please try it. Thanks for the proposal! @Ramblurr 

https://user-images.githubusercontent.com/9639995/177367627-e02685d2-894d-4580-8d7e-60f754e953e8.mov
