### ISSUE TITLE
Disable comments should match indent

### ISSUE THREAD

**Issue by DerekTBrown** [mizdra/eslint-interactive#216]
When applying the `disablePerLine` fix, the added lines are always at column 0 in the file, rather than matching the outer level of indent:

```
// eslint-disable-next-line you-dont-need-lodash-underscore/flatten -- TODO: Use ES6 instead of Underscore/Lodash.
    return _.flatten(
```

By default, we should match the level of indent of the line failing the linter.

**Comment by mizdra** [comment]
This feature was released by [v10.2.0](https://github.com/mizdra/eslint-interactive/releases/tag/v10.2.0). Thanks for the proposal! @DerekTBrown
