### ISSUE TITLE
allow passing ESLint's `--ignore-path` flag

### ISSUE THREAD

**Issue by B2o5T** [mizdra/eslint-interactive#243]
it's useful to provide `.gitignore` as `--ignore-path` for ESLint. Unfornutelly currently with `eslint-interactive` is impossible so he stucks in my project until I figured that he lint all ignored files `node_modules/`, `dist/`, etc.

**Comment by mizdra** [comment]
Thanks for your proposal! I can probably implement it easily. I will try it later.

**Comment by mizdra** [comment]
@B2o5T This feature shipped in v10.3.0. Please check it out :)

https://github.com/mizdra/eslint-interactive/releases/tag/v10.3.0

**Comment by B2o5T** [comment]
@mizdra Amazing, thank you for this library btw 🥳
