### ISSUE TITLE
Support the ability to add a comment prefix to explain WHY something was disabled per line.

### ISSUE THREAD

**Issue by subskribe-kevin** [mizdra/eslint-interactive#247]
There are times when we want to NEVER fix an eslint rule ... we know we're doing something wrong so we document WHY we are doing it.

Other code is just grandfathered in so I want to add a GRANDFATHERED prefix to it ... so we can determine that this code needs to be fixed.  

It's great that you can suppress per line but it would be better to also add a custom comment there.

**Comment by mizdra** [comment]
Thanks for the proposal!

To clarify the proposal: What you want to do is just insert a comment before the line with the error or warning? Does it not fix the error or warning, nor ignore it with the `// eslint-disable-next-line` directive, but just insert a comment?

eslint-interative can add comments when inserting eslint-disable-next-line directive (e.g. `// eslint-disable-next-line semi -- TODO: add semicolon. `). However, at this time it is not possible to insert only comments (e.g. `// TODO: add semicolon.`). Thus, if your proposal is for a feature like the above, it would be worth implementing.

**Comment by mizdra** [comment]
Perhaps the action `Make forcibly fixable and run eslint --fix` could solve your problem without implementing new features. This action can convert any error or warning into something fixable and run `eslint --fix`.

It is difficult to use without knowledge of ESLint's ASTs... I believe this would allow you to insert only TODO comments.

The script to pass to the action:
```typescript
// @ts-check

/**
 * A function to convert `Linter.LintMessage` to `Rule.Fix`.
 * @param {import('eslint').Linter.LintMessage} message - The `Linter.LintMessage` to be converted.
 * @param {import('estree').Node | null} node - The node corresponding to the message.
 * @param {import('eslint-interactive').FixContext} context - The context of the fix.
 * @returns {import('eslint').Rule.Fix | null | undefined} The `Rule.Fix` converted from `Linter.LintMessage`. If null or undefined, the message is not fixable.
 */
function fixableMaker(message, node, context) {
  if (message.ruleId === "semi") {
    const index = context.sourceCode.getIndexFromLoc({
      line: message.line,
      column: 0,
    });
    const comment = "// TODO: add semicolon.";
    return context.fixer.insertTextBeforeRange([index, index], comment + "\n");
  } else {
    return null;
  }
}

fixableMaker;
```

**Comment by mizdra** [comment]
@subskribe-kevin Could you please check if the following solution solves your problem? If your solution is not sufficient, please give me the details!
