### ISSUE TITLE
Add disable comments automatically without interactive mode

### ISSUE THREAD

**Issue by legend80s** [mizdra/eslint-interactive#303]
Consider a project with 100+ lint errors, if  run `npx eslint-interactive src --quiet`, the user should select all the rules and enter many times to answer all the questions. **It takes a long time!**

Can we fill the answers in the cli params? like below?

```
npx eslint-interactive --quiet --method disable-perf-line --comment 'not modify legacy code'
``` 

The command above will add `// @eslint-disable-next-line r1,r2,... -- not modify legacy code`  to  all error files **in one shot!**

**Comment by mizdra** [comment]
For the complex worflow, eslint-interactive provides Programmable API. This allows you add disable comments automatically without interactive mode.

- https://github.com/mizdra/eslint-interactive/blob/main/docs/programmable-api.md

Does this satisfy your use case?

**Comment by mizdra** [comment]
I think this use case is covered by the Programmable API. Therefore, I will close this issue. Thanks for sending in your feature request!
