### ISSUE TITLE
Disable per file or per line depending on the number of issues?

### ISSUE THREAD

**Issue by laurent22** [mizdra/eslint-interactive#353]
I often use eslint-interactive to automatically disable errors per line. However when there are many errors I think it would make sense to disable per file instead. Those are usually older files that are rarely changed so disabling per file would reduce noise.

So for example if there are more than 5 errors in a file, disable for the whole file, otherwise disable per line.

Any idea if that can be done at the moment? I've looked at the "Apply suggestions" action but it's not clear if it can be done this way. Any ideas?

**Comment by mizdra** [comment]
Thanks for using eslint-interactive!

I recommend using the Prograbbable API. The Prograbbable API supports the complex use cases you want. Could you try it?

https://github.com/mizdra/eslint-interactive/blob/main/docs/programmable-api.md

**Comment by mizdra** [comment]
Please check the Prograbbable API. If your problem is not solved, let me know.
