### ISSUE TITLE
Support disable ESLint for a block

### ISSUE THREAD

**Issue by sanjpareek** [mizdra/eslint-interactive#357]
I am introducing ESLint rules for JSDocs and there are multiline violations across files. 
Is it possible to use this lib for disabling ESLint violations for a block of code? 

<img width="278" alt="Screenshot 2024-05-17 at 7 16 07 AM" src="https://github.com/mizdra/eslint-interactive/assets/772184/88e856f6-beaa-4127-bc8e-8b9ab04bd143">

**Comment by mizdra** [comment]
Hmmm. Perhaps it is possible. Have you tried it? 

If it is not possible, please tell me the name of the rule that could not be disabled.

**Comment by mizdra** [comment]
@sanjpareek Check out https://github.com/mizdra/eslint-interactive/issues/357#issuecomment-2117413995. If the problem is not solved, open the issue again.
