### ISSUE TITLE
Will this not work for custom Rules

### ISSUE THREAD

**Issue by ViditaRustagi** [mizdra/eslint-interactive#361]
I have created a custom eslint rule, want to suppress the violations using this library, but it doesn't work. No error thrown but not able to suppress the errors as well

**Comment by mizdra** [comment]
Can you load the custom rules with ESLint? eslint-interactive can load custom rules just like ESLint. Could you first make sure that the custom rules can be loaded by ESLint?

**Comment by mizdra** [comment]
This issue is closed due to lack of information.
