### ISSUE TITLE
Cannot save fixes when using legacy config (`eslintrc`) and typescript-eslint

### ISSUE THREAD

**Issue by uhyo** [mizdra/eslint-interactive#364]
Hello, thank you for the great tool! 😀 

I'm having trouble using the latest version (11.0.3) of `eslint-interactive` combined with legacy config (`eslintrc`) and typescript-eslint.

## Problem Description

eslint-interactive recognizes lint errors, but does not write fixes (`eslint-disable-next-line` comments in my case) to the file system.

Read mode details in a reproduction repository:

https://github.com/uhyo/eslint-interactive-issue-364-repro

## Additional Info

- Issue does not occur for `eslint-interactive@10`.
- Issue does not occur when using Flat Config.
- Issue seems to only occur when `@typescript-eslint/parser` is involved. (other third-party parsers not tested, sorry)

**Comment by mizdra** [comment]
Thank you for reporting! I could reproduce it. I will fix it.
