### ISSUE TITLE
add more fixable rules

### ISSUE THREAD

**Issue by odanado** [mizdra/eslint-interactive#64]
Thank you for great tool.

https://github.com/aladdin-add/eslint-plugin/tree/master/packages/autofix can increase the number of fixable rules.
More fixable rules are useful because they reduce the need to add disable comments.

**Comment by mizdra** [comment]
We had a conversation about this issue on twitter.

ref: https://twitter.com/mizdra/status/1469324224271888384

- @odanado was expecting eslint-interactive to bundle eslint-plugin-autofix
  - This allows users to use eslint-plugin-autofix rules on eslint-interactive without having to install eslint-plugin-autofix
  - For users who want to use eslint-plugin-autofix, this feature will be very useful.
- However, users can do the same thing by simply installing eslint-plugin-autofix.
  - It's also easier to understand what's going on.
- Therefore, eslint-interactive will not bundle eslint-plugin-autofix.
- On the other hand, having more modifiable rules is a good idea!
  - So we decided to implement https://github.com/mizdra/eslint-interactive/pull/76
- Thank you for inspiring me.
